# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIw3UCE407fbG4-5PyFq9tljFNOXkpY5
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

email_df = pd.read_csv("spam.csv", encoding='latin-1')[['v1', 'v2']]
email_df.columns = ['Threat', 'Message']

print("Class Balance:")
print(email_df['Threat'].value_counts())

text_converter = TfidfVectorizer(stop_words='english')
features = text_converter.fit_transform(email_df['Message'])
target = email_df['Threat']

train_x, test_x, train_y, test_y = train_test_split(
    features, target, test_size=0.2, random_state=42
)

email_classifier = SVC(kernel='linear', random_state=42)
email_classifier.fit(train_x, train_y)

predicted_labels = email_classifier.predict(test_x)

print("\nModel Performance")
print("Accuracy :", round(accuracy_score(test_y, predicted_labels), 2))
print("Precision:", round(precision_score(test_y, predicted_labels, pos_label='spam'), 2))
print("Recall   :", round(recall_score(test_y, predicted_labels, pos_label='spam'), 2))
print("F1 Score :", round(f1_score(test_y, predicted_labels, pos_label='spam'), 2))

matrix = confusion_matrix(test_y, predicted_labels, labels=['ham', 'spam'])
print("\nConfusion Matrix (rows=Actual, cols=Predicted):")
print(f"              ham   spam")
print(f"  ham     {matrix[0]}")
print(f"  spam    {matrix[1]}")

# Bug fix: use .loc not .iloc
test_messages = email_df.loc[test_y.index]['Message'].values

print("\nMisclassified Emails (first 5):")
found = False
count = 0

for msg, actual, predicted in zip(test_messages, test_y, predicted_labels):
    if actual != predicted:
        found = True
        count += 1
        print(f"Email    : {msg}")
        print(f"Actual   : {actual}  |  Predicted: {predicted}\n")
        if count == 5:
            break

if not found:
    print("No misclassified emails.")